name: ecg-stenosis-cls
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.0=py311h06a4308_0
  - python=3.11.11=he870216_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.10.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrdict==2.0.1
      - attrs==25.3.0
      - awscli==1.40.15
      - babel==2.17.0
      - backoff==2.2.1
      - beartype==0.21.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - bokeh==3.6.3
      - botocore==1.38.16
      - braceexpand==0.1.7
      - certifi==2025.8.3
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - click==8.2.1
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - dacite==1.8.1
      - debugpy==1.8.16
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.9
      - docker==7.1.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - docutils==0.19
      - ecg-plot==0.2.8
      - einops==0.8.1
      - executing==2.2.0
      - fastapi==0.115.8
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fire==0.7.0
      - fonttools==4.59.0
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.70.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.7
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - hydra-core==1.3.2
      - icd-mappings==0.4.0
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - imbalanced-learn==0.13.0
      - imblearn==0.0
      - importlib-resources==5.13.0
      - iopath==0.1.10
      - ipykernel==6.30.1
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - isort==6.0.1
      - iterative-stratification==0.1.9
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.1
      - joypy==0.2.6
      - json5==0.12.0
      - jsonargparse==4.37.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kernels==0.9.0
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - lightning==2.5.0.post0
      - lightning-sdk==0.1.55
      - lightning-utilities==0.15.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.3
      - mlstm-kernels==1.0.3
      - moviepy==2.1.2
      - mpmath==1.3.0
      - multidict==6.6.3
      - mypy==1.17.1
      - mypy-extensions==1.1.0
      - narwhals==1.27.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - neurokit2==0.2.10
      - nibabel==5.3.3
      - ninja==1.11.1.3
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - openai-harmony==0.0.4
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - packaging
      - pandarallel==1.6.5
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - peft==0.17.0
      - pexpect==4.9.0
      - pillow
      - platformdirs==4.3.8
      - plotly==6.0.0
      - portalocker==3.2.0
      - prettytable==3.13.0
      - proglog==0.1.10
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydeprecate==0.3.2
      - pydicom==3.0.1
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.2
      - pytorch-lightning-bolts==0.3.2.post1
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - pyzmq==27.0.1
      - rdkit==2024.9.5
      - referencing==0.36.2
      - regex==2025.7.34
      - reportlab==4.2.5
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==13.9.4
      - rpds-py==0.27.0
      - rsa==4.7.2
      - ruff==0.12.8
      - s3transfer==0.12.0
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn
      - scipy==1.16.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.34.1
      - setproctitle==1.3.4
      - setuptools==80.9.0
      - shellingham==1.5.4
      - simple-icd-10==2.1.1
      - simple-term-menu==1.6.6
      - six==1.17.0
      - sklearn-compat==0.1.3
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - starlette==0.45.3
      - sympy==1.14.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.6.11
      - timm==1.0.19
      - tinycss2==1.4.0
      - tokenizers==0.21.4
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchmetrics==1.8.1
      - torchvision==0.23.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.55.0
      - triton==3.4.0
      - typer==0.23.0
      - typer-slim==0.23.0
      - types-python-dateutil==2.9.0.20250809
      - typeshed-client==2.7.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - ultralytics==8.3.163
      - ultralytics-thop==2.0.14
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uvicorn==0.34.0
      - wandb==0.21.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wfdb==4.3.0
      - widgetsnbextension==4.0.14
      - xlstm==2.0.4
      - xyzservices==2025.1.0
      - yarl==1.20.1
