name: stence
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.6.2=py311h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311h06a4308_0
  - attrs=24.2.0=py311h06a4308_0
  - babel=2.11.0=py311h06a4308_0
  - beautifulsoup4=4.12.3=py311h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cffi=1.17.1=py311h1fdaa30_0
  - comm=0.2.1=py311h06a4308_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.6=3
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py311h06a4308_0
  - httpcore=1.0.2=py311h06a4308_0
  - httpx=0.27.0=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py311h06a4308_0
  - ipython=8.27.0=py311h06a4308_0
  - ipywidgets=8.1.2=py311h06a4308_0
  - jedi=0.19.1=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py311h06a4308_0
  - jsonschema=4.23.0=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter=1.0.0=py311h06a4308_9
  - jupyter-lsp=2.2.0=py311h06a4308_0
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - jupyter_events=0.10.0=py311h06a4308_0
  - jupyter_server=2.14.1=py311h06a4308_0
  - jupyter_server_terminals=0.4.4=py311h06a4308_1
  - jupyterlab=4.2.5=py311h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py311h06a4308_0
  - jupyterlab_widgets=3.0.10=py311h06a4308_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.11.1.6=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.7.77=0
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.6.77=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.0=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mistune=2.0.4=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - mysql=8.4.0=h29a9f33_1
  - nbclient=0.8.0=py311h06a4308_0
  - nbconvert=7.16.4=py311h06a4308_0
  - nbformat=5.10.4=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=7.2.2=py311h06a4308_1
  - notebook-shim=0.2.3=py311h06a4308_0
  - numexpr=2.10.1=py311h3c60e43_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.4.1=h7b32b05_0
  - overrides=7.4.0=py311h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=24.2=py311h06a4308_0
  - ply=3.11=py311h06a4308_0
  - prometheus_client=0.14.1=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydicom=3.0.1=pyhd8ed1ab_2
  - pyqt=5.15.10=py311h6a678d5_0
  - pyqt5-sip=12.13.0=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.10=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-fastjsonschema=2.16.2=py311h06a4308_0
  - python-json-logger=2.0.7=py311h06a4308_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=25.1.2=py311h6a678d5_0
  - qt-main=5.15.2=hb6262e9_11
  - qtconsole=5.6.0=py311h06a4308_0
  - qtpy=2.4.1=py311h06a4308_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rpds-py=0.10.6=py311hb02cf49_0
  - send2trash=1.8.2=py311h06a4308_0
  - setuptools=75.1.0=py311h06a4308_0
  - sip=6.7.12=py311h6a678d5_0
  - sniffio=1.3.0=py311h06a4308_0
  - soupsieve=2.5=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=py311h06a4308_0
  - tinycss2=1.2.1=py311h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py311h5eee18b_0
  - traitlets=5.14.3=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=1.8.0=py311h06a4308_0
  - wheel=0.44.0=py311h06a4308_0
  - widgetsnbextension=4.0.10=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - blosc2==3.5.1
      - cachetools==5.5.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - chex==0.1.89
      - click==8.1.7
      - contourpy==1.3.3
      - coverage==7.13.0
      - cycler==0.12.1
      - dacite==1.9.2
      - deprecated==1.2.15
      - dicom2nifti==2.5.1
      - docker-pycreds==0.4.0
      - ecg-plot==0.2.8
      - einops==0.8.2
      - et-xmlfile==2.0.0
      - etils==1.12.2
      - filelock==3.18.0
      - filetype==1.2.0
      - flax==0.10.6
      - fonttools==4.61.0
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - geojson==3.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.23.0
      - google-auth==2.36.0
      - googleapis-common-protos==1.66.0
      - grpcio==1.76.0
      - h5py==3.14.0
      - huggingface-hub==0.24.0
      - humanize==4.11.0
      - hydra-core==1.3.2
      - ignite==1.1.0
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.4.5
      - iniconfig==2.3.0
      - iopath==0.1.10
      - ishneholterlib==2017.4.11
      - jax==0.6.0
      - jaxlib==0.6.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - joypy==0.2.6
      - kiwisolver==1.4.9
      - labelbox==6.1.0
      - lazy-loader==0.4
      - lbox-clients==1.1.1
      - lightning-utilities==0.14.3
      - llvmlite==0.46.0
      - markdown==3.10
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mlstm-kernels==2.0.2
      - momentfm==0.1.4
      - msgpack==1.1.0
      - multidict==6.4.3
      - mypy==1.10.1
      - mypy-extensions==1.0.0
      - ndindex==1.10.0
      - networkx==3.4.2
      - nibabel==5.3.2
      - ninja==1.13.0
      - nose==1.3.7
      - numba==0.63.1
      - numpy
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.11.12
      - packaging==24.2
      - pandas==2.3.3
      - pi-heif==1.1.1
      - pillow==12.0.0
      - pillow-avif-plugin==1.5.2
      - platformdirs==4.3.6
      - pluggy==1.6.0
      - portalocker==3.1.1
      - propcache==0.3.1
      - proto-plus==1.25.0
      - protobuf==5.28.3
      - psutil==6.1.0
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycrc==0.11.0
      - pydantic==2.10.1
      - pydantic-core==2.27.1
      - pyecg==0.0.9.1
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pytest==9.0.2
      - pytest-cov==7.0.0
      - python-dotenv==1.2.1
      - python-gdcm==3.0.24.1
      - python-ternary==1.0.8
      - pythoncrc==1.21
      - pytorch-lightning==2.5.1.post0
      - pytz==2025.2
      - regex==2024.11.6
      - reportlab==4.4.10
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - roboflow==1.2.11
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.18.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - simpleitk==2.4.0
      - simplejson==3.20.1
      - six==1.17.0
      - sklearn==0.0.post12
      - smmap==5.0.1
      - soundfile==0.13.1
      - strenum==0.4.15
      - supervision==0.27.0
      - sympy==1.13.1
      - tables==3.10.2
      - tabulate==0.9.0
      - taming-transformers==0.0.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.74
      - termcolor==2.5.0
      - ternary==0.1
      - threadpoolctl==3.6.0
      - tifffile==2025.3.13
      - timm==1.0.11
      - tokenizers==0.19.1
      - toolz==1.0.0
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchio==0.20.3
      - torchmetrics==1.7.1
      - torchvision==0.21.0
      - tqdm==4.67.0
      - transformers
      - treescope==0.1.9
      - triton==3.2.0
      - typer==0.15.1
      - typing-extensions==4.13.0
      - tzdata==2025.2
      - ultralytics==8.3.136
      - ultralytics-thop==2.0.14
      - umap-learn==0.5.9.post2
      - urllib3==2.6.1
      - wandb==0.18.6
      - werkzeug==3.1.4
      - wfdb==2.2.1
      - wrapt==1.17.0
      - xformers==0.0.29.post3
      - xgboost==3.0.5
      - xlstm==2.0.5
      - yacs==0.1.8
      - yarl==1.20.0
      - zipp==3.23.0
